// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


async function getAsyncData(msg) {
  console.log(msg);
}

getAsyncData("hello world");

exports.getAsyncData = getAsyncData;
/*  Not a pure module */
