// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Koa = require("koa").default;

var app = new Koa();

app.env = "development";

app.use(async function (context, next) {
      console.log("1");
      console.log(context.request.ip);
      context.body = "hello";
      await next();
      console.log("2");
    });

app.use(async function (param, next) {
      console.log("3");
      await next();
      console.log("4");
    });

app.listen(8080, (function (param) {
        console.log("server is start success!");
      }));

exports.app = app;
/* app Not a pure module */
