// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Koa = require("koa").default;
var Curry = require("rescript/lib/js/curry.js");

var app = new Koa({});

app.use(async function (context, next) {
      console.log("1");
      context.body = "hello";
      await Curry._1(next, undefined);
      console.log("2");
    });

app.use(async function (param, next) {
      console.log("3");
      await Curry._1(next, undefined);
      console.log("4");
    });

app.env = "哈哈哈";

app.listen(3000, "127.0.0.1", (function (param) {
        console.log("哈哈哈");
      }));

app.on("error", (function (err, ctx) {
        console.log(err);
      }));

exports.app = app;
/* app Not a pure module */
