// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var Req = {};

var Res = {};

var Ctx = {};

var App = {};

var Special = {};

exports.Req = Req;
exports.Res = Res;
exports.Ctx = Ctx;
exports.App = App;
exports.Special = Special;
/* No side effect */
